resources:
- knative-operator.yaml
- serving.yaml
- https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.1/components.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kubelet-insecure-tls
  target:
    kind: Deployment
    name: metrics-server
    namespace: kube-system
    version: v1
