apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/ricochet/helloworld-go
        env:
        - name: TARGET
          value: "Go Sample v1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/ricochet/helloworld-nodejs
        env:
        - name: TARGET
          value: "Node.js Sample v1"
