apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: validator-${UNIQUE_ID}
  namespace: validators
  annotations:
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "5"
spec:
  template:
    spec:
      containers:
      - name: validator
        image: validator-function:latest
        ports:
        - containerPort: 8080
        env:
        - name: VALIDATOR_ID
          value: "${UNIQUE_ID}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"