apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: validator-${UNIQUE_ID}
  namespace: validators
spec:
  template:
    spec:
      containers:
      - name: validator
        image: ghcr.io/ricochet/validator-function:latest
        env:
        - name: VALIDATOR_ID
          value: "${UNIQUE_ID}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "30Mi"
            cpu: "1m"
